### PR TITLE
Clarify summary challenge

### PR DESCRIPTION
**Pull request by cmacdonell**
Added a simple artificial example to illustrate unstack() and added an ultimate solution.

### CODE REVIEW

**Comment by hlapp** [comment]
@kcranston, @ethanwhite, or @tracykteal - could you check? It seems good to me, but I'm not the expert for this lesson.

**Comment by ethanwhite** [comment]
These changes look good to me, and given that we're currently introducing new approaches that haven't been covered in the lecture in the challenge I think more detail is warranted.

**Comment by tracykteal** [comment]
Thanks @cmacdonell for the PR. @wrightaprilm or @qjcg would you have a chance to review?

**Comment by qjcg** [comment]
Sure @tracykteal, I'll be happy to go through this this evening and send along any comments I may have.

**Comment by ethanwhite** [comment]
Just so everyone is clear, this PR has been merged already.

**Comment by qjcg** [comment]
I'm just here to lend a hand! Please let me know if review is no longer needed, otherwise I'll send along feedback as requested.

**Comment by ethanwhite** [comment]
Input on any aspect of the material is always useful, but since this PR has been merged it's probably more useful in a separate issue at this point. That said, I'm not maintaining this lesson so that's just my opinion. It just looked like the conversation was proceeding as if this PR was still open and I wanted to make sure folks knew what its status was.

**Pull request merged**
