### PR TITLE
More edits post workshop presentation at NCAR

### PR DESCRIPTION
**Pull request by lwasser**
HI Tracy,
I've added a series of additional edits to the lessons that incorporate feedback from the workshop we gave at NCAR.

leah

### CODE REVIEW

**Comment by lwasser** [comment]
@tracykteal will you have a look and merge this PR if you are happy with it? i'm going to work on a few more edits soon as well.

**Comment by lwasser** [comment]
Hi @tracykteal - i added another modification to lesson 04. More feedback from the lesson. I think the text could be cut down in this lesson - it's wordy. but the content is good. 
leah

**Comment by tracykteal** [comment]
Thanks @lwasser! These are great changes for improvement and clarity. Sorry about the slow response to the PR.

Just a couple points
- We need to add April Wright in the contributing sections. She was the person who did the translation of the R lesson to Python. 
- I'm not sure about the jellybean.py script. Is that a capstone lesson?

**Comment by lwasser** [comment]
HI @tracykteal ,
Definitely. I've removed the jellybean file. That was a wrap up activity but it's not fleshed out as a proper lesson!
I added April as well. :)

**Comment by tracykteal** [comment]
Thanks, looks good!

**Pull request merged**
